# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Upgrade and Rollback Module.

Combined module for Omnia upgrade and rollback workflows.
"""

from .functions import (
    # Common
    compare_versions,
    # Upgrade
    validate_upgrade_versions,
    validate_versions,
    validate_config,
    check_backup_exists,
    check_pre_upgrade_container,
    clone_upgrade_repo,
    build_core_image,
    verify_podman_image,
    download_omnia_sh,
    run_omnia_upgrade,
    verify_backup_directory,
    verify_post_upgrade_state,
    run_prepare_upgrade,
    verify_backup_md5sum,
    # Rollback
    verify_rollback_precondition,
    check_rollback_image,
    download_omnia_sh_for_rollback,
    run_omnia_rollback,
    verify_rollback_container,
    verify_rollback_backup_md5sum,
    # K8s & Telemetry pre-check collectors
    collect_k8s_node_versions,
    collect_node_readiness,
    collect_kube_system_pods,
    collect_etcd_health,
    collect_calico_status,
    collect_metallb_status,
    collect_lb_service_ips,
    collect_helm_releases,
    collect_telemetry_pods,
    collect_vm_pvcs,
    collect_kafka_state,
    collect_csi_status,
    collect_nfs_provisioner,
    collect_crio_version,
    collect_calico_version,
    collect_network_policies,
    collect_metallb_version,
    collect_helm_version,
    collect_idrac_telemetry_status,
    collect_ldms_status,
    verify_ssh_connectivity,
    verify_version_hop_valid,
    verify_oim_upgrade_completed,
    collect_telemetry_config_flags,
    collect_etcd_backup_status,
    collect_security_permissions,
    verify_pulp_images_available,
    verify_addon_compatibility,
    verify_k8s_at_target_for_telemetry,
    verify_telemetry_preflight,
    collect_bss_boot_params,
    collect_strimzi_version,
    collect_crio_storage_config,
    collect_kube_vip_status,
    collect_pod_disruption_budgets,
    collect_node_roles,
    # K8s & Telemetry post-check verifiers
    verify_k8s_target_version,
    verify_all_nodes_ready,
    verify_kube_system_healthy,
    verify_etcd_healthy,
    verify_api_server_reachable,
    verify_dns_resolution,
    verify_calico_healthy,
    verify_metallb_ips_preserved,
    verify_telemetry_pods_running,
    verify_vm_pvcs_preserved,
    verify_vm_data_accessible,
    verify_kafka_topics_preserved,
    verify_csi_pvcs_preserved,
    verify_helm_releases_present,
    verify_crio_at_target,
    verify_calico_version_upgraded,
    verify_network_policies_preserved,
    verify_metallb_version_upgraded,
    verify_helm_at_target,
    verify_nfs_provisioner_running,
    verify_idrac_telemetry_running,
    verify_ldms_collecting,
    verify_new_telemetry_components,
    verify_upgrade_manifest,
    verify_cps_at_target,
    verify_workers_at_target,
    verify_etcd_backup_exists,
    verify_pdbs_healthy,
    verify_crio_storage_preserved,
    verify_bss_params_updated,
    verify_kube_vip_ha,
    verify_strimzi_upgraded,
    verify_kraft_migration,
    verify_telemetry_phase1_gate,
    verify_security_permissions,
    verify_cluster_unchanged,
    verify_rollback_to_source,
    verify_rollback_etcd_restored,
    verify_rollback_helm_restored,
    verify_rollback_telemetry_healthy,
    verify_rollback_metallb_cleaned,
    verify_rollback_csi_cleaned,
    # Snapshot persistence
    save_precheck_snapshot,
    load_precheck_snapshot,
)
from .vars import (
    UPGRADE_VARS,
    SUPPORTED_VERSIONS,
    VERSION_PROPERTIES,
    get_core_tag_for_version,
    PREPARE_UPGRADE_VARS,
    BACKUP_VERIFY_VARS,
    ROLLBACK_VARS,
    # K8s & Telemetry upgrade
    K8S_UPGRADE_VARS,
    SNAPSHOT_PATH,
    TELEMETRY_NAMESPACE,
)
from .messages import (
    # Upgrade messages
    TEST_NAMES,
    TEST_LOG_MSGS,
    TEST_ASSERT_MSGS,
    SKIP_MSGS,
    BACKUP_TEST_NAMES,
    BACKUP_LOG_MSGS,
    BACKUP_ASSERT_MSGS,
    BACKUP_SKIP_MSGS,
    PREPARE_TEST_NAMES,
    PREPARE_LOG_MSGS,
    PREPARE_ASSERT_MSGS,
    PREPARE_SKIP_MSGS,
    # Rollback messages
    ROLLBACK_TEST_NAMES,
    ROLLBACK_LOG_MSGS,
    ROLLBACK_ASSERT_MSGS,
    ROLLBACK_SKIP_MSGS,
    # K8s & Telemetry upgrade messages
    PRECHECK_TEST_NAMES,
    PRECHECK_LOG_MSGS,
    PRECHECK_ASSERT_MSGS,
    POSTCHECK_TEST_NAMES,
    POSTCHECK_LOG_MSGS,
    POSTCHECK_ASSERT_MSGS,
    K8S_TEL_SKIP_MSGS,
)

__all__ = [
    # Common functions
    "compare_versions",
    # Upgrade functions
    "validate_upgrade_versions",
    "validate_versions",
    "validate_config",
    "check_backup_exists",
    "check_pre_upgrade_container",
    "clone_upgrade_repo",
    "build_core_image",
    "verify_podman_image",
    "download_omnia_sh",
    "run_omnia_upgrade",
    "verify_backup_directory",
    "verify_post_upgrade_state",
    "run_prepare_upgrade",
    "verify_backup_md5sum",
    # Rollback functions
    "verify_rollback_precondition",
    "check_rollback_image",
    "download_omnia_sh_for_rollback",
    "run_omnia_rollback",
    "verify_rollback_container",
    "verify_rollback_backup_md5sum",
    # Vars
    "UPGRADE_VARS",
    "SUPPORTED_VERSIONS",
    "VERSION_PROPERTIES",
    "get_core_tag_for_version",
    "PREPARE_UPGRADE_VARS",
    "BACKUP_VERIFY_VARS",
    "ROLLBACK_VARS",
    # Messages
    "TEST_NAMES",
    "TEST_LOG_MSGS",
    "TEST_ASSERT_MSGS",
    "SKIP_MSGS",
    "BACKUP_TEST_NAMES",
    "BACKUP_LOG_MSGS",
    "BACKUP_ASSERT_MSGS",
    "BACKUP_SKIP_MSGS",
    "PREPARE_TEST_NAMES",
    "PREPARE_LOG_MSGS",
    "PREPARE_ASSERT_MSGS",
    "PREPARE_SKIP_MSGS",
    "ROLLBACK_TEST_NAMES",
    "ROLLBACK_LOG_MSGS",
    "ROLLBACK_ASSERT_MSGS",
    "ROLLBACK_SKIP_MSGS",
    # K8s & Telemetry pre-check collectors
    "collect_k8s_node_versions",
    "collect_node_readiness",
    "collect_kube_system_pods",
    "collect_etcd_health",
    "collect_calico_status",
    "collect_metallb_status",
    "collect_lb_service_ips",
    "collect_helm_releases",
    "collect_telemetry_pods",
    "collect_vm_pvcs",
    "collect_kafka_state",
    "collect_csi_status",
    "collect_nfs_provisioner",
    "collect_crio_version",
    "collect_calico_version",
    "collect_network_policies",
    "collect_metallb_version",
    "collect_helm_version",
    "collect_idrac_telemetry_status",
    "collect_ldms_status",
    "verify_ssh_connectivity",
    "verify_version_hop_valid",
    "verify_oim_upgrade_completed",
    "collect_telemetry_config_flags",
    "collect_etcd_backup_status",
    "collect_security_permissions",
    "verify_pulp_images_available",
    "verify_addon_compatibility",
    "verify_k8s_at_target_for_telemetry",
    "verify_telemetry_preflight",
    "collect_bss_boot_params",
    "collect_strimzi_version",
    "collect_crio_storage_config",
    "collect_kube_vip_status",
    "collect_pod_disruption_budgets",
    "collect_node_roles",
    # K8s & Telemetry post-check verifiers
    "verify_k8s_target_version",
    "verify_all_nodes_ready",
    "verify_kube_system_healthy",
    "verify_etcd_healthy",
    "verify_api_server_reachable",
    "verify_dns_resolution",
    "verify_calico_healthy",
    "verify_metallb_ips_preserved",
    "verify_telemetry_pods_running",
    "verify_vm_pvcs_preserved",
    "verify_vm_data_accessible",
    "verify_kafka_topics_preserved",
    "verify_csi_pvcs_preserved",
    "verify_helm_releases_present",
    "verify_crio_at_target",
    "verify_calico_version_upgraded",
    "verify_network_policies_preserved",
    "verify_metallb_version_upgraded",
    "verify_helm_at_target",
    "verify_nfs_provisioner_running",
    "verify_idrac_telemetry_running",
    "verify_ldms_collecting",
    "verify_new_telemetry_components",
    "verify_upgrade_manifest",
    "verify_cps_at_target",
    "verify_workers_at_target",
    "verify_etcd_backup_exists",
    "verify_pdbs_healthy",
    "verify_crio_storage_preserved",
    "verify_bss_params_updated",
    "verify_kube_vip_ha",
    "verify_strimzi_upgraded",
    "verify_kraft_migration",
    "verify_telemetry_phase1_gate",
    "verify_security_permissions",
    "verify_cluster_unchanged",
    "verify_rollback_to_source",
    "verify_rollback_etcd_restored",
    "verify_rollback_helm_restored",
    "verify_rollback_telemetry_healthy",
    "verify_rollback_metallb_cleaned",
    "verify_rollback_csi_cleaned",
    # Snapshot persistence
    "save_precheck_snapshot",
    "load_precheck_snapshot",
    # K8s & Telemetry vars
    "K8S_UPGRADE_VARS",
    "SNAPSHOT_PATH",
    "TELEMETRY_NAMESPACE",
    # K8s & Telemetry messages
    "PRECHECK_TEST_NAMES",
    "PRECHECK_LOG_MSGS",
    "PRECHECK_ASSERT_MSGS",
    "POSTCHECK_TEST_NAMES",
    "POSTCHECK_LOG_MSGS",
    "POSTCHECK_ASSERT_MSGS",
    "K8S_TEL_SKIP_MSGS",
]
