{
 "title": "ldms",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "System", "query": "systemA,systemB,systemC" },
   { "name": "loki", "query": "loki" },
   { "name": "prometheus", "query": "prometheus" },
   { "name": "ldms", "query": "prometheus" },
   { "name": "ldms_data", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Metric Rates Fedelity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "sample rates: login+service+ncn (metric_set/minute)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"login.+\"}[10m])/10) by(hostname) default 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"service.+\"}[10m])/10) by(hostname) default 0",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"ncn.+\"}[10m])/10) by(hostname) default 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "sample rates: dcgm (metric_set/minute)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time(nersc_ldms_dcgm_memory_clock{hostname=~\"nid.+\"}[10m])/10) by(hostname,gpu_id) default 0",
     "legendFormat": "{{hostname}}.{{gpu_id}}"
    }
   ]
  },
  {
   "title": "sample rates: all compute (metric_set/minute)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"nid.+\"}[10m])/10) by(hostname) default 0",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "LDMS Producer Host Count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Application Nodes: Login, Workflow, Service",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum(group by (hostname) (nersc_ldms_loadavg_load15min{hostname=~\"login.+\"})) default 0",
     "legendFormat": "Login"
    },
    {
     "expr": "sum(group by (hostname) (nersc_ldms_loadavg_load15min{hostname=~\"service.+\"})) default 0",
     "legendFormat": "Service"
    },
    {
     "expr": "sum(group by (hostname) (nersc_ldms_loadavg_load15min{hostname=~\"work.+\"})) default 0",
     "legendFormat": "Workflow"
    }
   ]
  },
  {
   "title": "Compute Nodes: CPU & GPU",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "count(sum(count_over_time(nersc_ldms_dcgm_fb_free{hostname=~\"nid.+\"}[10m])) by (hostname)) default 0",
     "legendFormat": "GPU"
    },
    {
     "expr": "count(sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"nid.+\"})[1h]) by(hostname)) - count(sum(count_over_time(nersc_ldms_dcgm_fb_free{hostname=~\"nid.+\"})[1h]) by(hostname)) default 0",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Management Nodes: ncn",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "count(sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"ncn-s.+\"})[1h]) by(hostname)) default 0",
     "legendFormat": "ncn-s"
    },
    {
     "expr": "count(sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"ncn-m.+\"})[1h]) by(hostname)) default 0",
     "legendFormat": "ncn-m"
    },
    {
     "expr": "count(sum(count_over_time(nersc_ldms_loadavg_load15min{hostname=~\"ncn-w.+\"})[1h]) by(hostname)) default 0",
     "legendFormat": "ncn-w"
    }
   ]
  },
  { "title": "LDMSD Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Total metric sets",
   "type": "timeseries",
   "description": "From ldms_ls, \"Total Sets\". This is the sum from all ldms store daemons.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(ldmsd_metric_total_sets{__ignore_usage__=\"\",ldms_type=\"store\"} ) by(ldms_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total metric data (kb)",
   "type": "timeseries",
   "description": "From ldms_ls, \"Data (kB)\". This is the sum from all ldms store daemons.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(ldmsd_metric_data_kb{__ignore_usage__=\"\", ldms_type=\"store\"} ) by(ldms_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total meta-data (kb)",
   "type": "timeseries",
   "description": "From ldms_ls, \"Meta Data (kB)\". This is the sum from all ldms store daemons.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(ldmsd_metric_meta_data_kb{__ignore_usage__=\"\", ldms_type=\"store\"} ) by(ldms_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total memory (kb)",
   "type": "timeseries",
   "description": "From ldms_ls, \"Memory (kB)\". This is the sum from all ldms store daemons.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "targets": [
    {
     "expr": "sum(ldmsd_metric_memory_kb{__ignore_usage__=\"\", ldms_type=\"store\"} ) by(ldms_group)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metric sets per comp-gpu-agg",
   "type": "timeseries",
   "description": "From ldms_ls, \"Total Sets\". This is for each gpu agg.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "ldmsd_metric_total_sets{__ignore_usage__=\"\", ldms_type=\"agg\", ldms_group=\"comp-gpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Metric sets per comp-cpu-agg",
   "type": "timeseries",
   "description": "From ldms_ls, \"Total Sets\". This is for each cpu agg.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 18 },
   "targets": [
    {
     "expr": "ldmsd_metric_total_sets{__ignore_usage__=\"\", ldms_type=\"agg\", ldms_group=\"comp-cpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Metric sets per comp-cpu-store",
   "type": "timeseries",
   "description": "From ldms_ls, \"Total Sets\". This is for each  cpu store.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "ldmsd_metric_total_sets{__ignore_usage__=\"\", ldms_type=\"store\", ldms_group=\"comp-cpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Metric sets per comp-gpu-store",
   "type": "timeseries",
   "description": "From ldms_ls, \"Total Sets\". This is for each gpu store.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 18 },
   "targets": [
    {
     "expr": "ldmsd_metric_total_sets{__ignore_usage__=\"\", ldms_type=\"store\", ldms_group=\"comp-gpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Producer per comp-gpu-agg",
   "type": "timeseries",
   "description": "The number of producers with a meminfo sampler, for each gpu agg",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "ldmsd_metric_sampler_count{sampler_type=\"meminfo\", ldms_type=\"agg\", ldms_group=\"comp-gpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Producer per comp-cpu-agg",
   "type": "timeseries",
   "description": "The number of producers with a meminfo sampler, for each cpu agg",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "ldmsd_metric_sampler_count{sampler_type=\"meminfo\", ldms_type=\"agg\", ldms_group=\"comp-cpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Producer per comp-gpu-store",
   "type": "timeseries",
   "description": "The number of producers with a meminfo sampler, for each gpu store",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "ldmsd_metric_sampler_count{sampler_type=\"meminfo\", ldms_type=\"store\", ldms_group=\"comp-gpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Producer per comp-cpu-store",
   "type": "timeseries",
   "description": "The number of producers with a meminfo sampler, for each cpu store",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 23 },
   "targets": [
    {
     "expr": "ldmsd_metric_sampler_count{sampler_type=\"meminfo\", ldms_type=\"store\", ldms_group=\"comp-cpu\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Producer per appl and man, agg and store ",
   "type": "timeseries",
   "description": "The number of producers with a meminfo sampler, for application and management nodes, for both agg and store",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 28 },
   "targets": [
    {
     "expr": "ldmsd_metric_sampler_count{sampler_type=\"meminfo\", ldms_group=\"appl\"}",
     "legendFormat": "{{ldms_name}}"
    },
    {
     "expr": "ldmsd_metric_sampler_count{sampler_type=\"meminfo\", ldms_group=\"mana\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Metric sets per appl and man, agg and store",
   "type": "timeseries",
   "description": "From ldms_ls, \"Total Sets\". This is for each Application and Management, for agg and store",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 28 },
   "targets": [
    {
     "expr": "ldmsd_metric_total_sets{__ignore_usage__=\"\", ldms_group=\"appl\"}",
     "legendFormat": "{{ldms_name}}"
    },
    {
     "expr": "ldmsd_metric_total_sets{__ignore_usage__=\"\", ldms_group=\"mana\"}",
     "legendFormat": "{{ldms_name}}"
    }
   ]
  },
  {
   "title": "Prouder stats connected count. Needs Work",
   "type": "timeseries",
   "description": "From metrics prdcr_stats, connected count. This needs work.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 28 },
   "targets": [
    {
     "expr": "sum(count_over_time(ldmsd_metric_prdcr_stats_connected_count[10m])) by(ldms_group,ldms_type)",
     "legendFormat": "{{ldms_group}}-{{ldms_type}}"
    }
   ]
  },
  {
   "title": "Aggregators and Storage daemons",
   "type": "timeseries",
   "description": "Count the number of store and agg daemons",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 28 },
   "targets": [
    {
     "expr": "count(count(container_memory_usage_bytes{container=~\"appl\"}) by(container))",
     "legendFormat": "appl-agg"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{container=~\"comp-cpu.+\"}) by(container))",
     "legendFormat": "comp-cpu-agg"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{container=~\"comp-gpu.+\"}) by(container))",
     "legendFormat": "comp-gpu-agg"
    },
    {
     "expr": "count(count(container_memory_usage_bytes{container=~\"mana\"}) by(container))",
     "legendFormat": "mana-agg"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"nersc-ldms-store-appl.+\"})",
     "legendFormat": "appl-store"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"nersc-ldms-store-compute-cpu.+\"})",
     "legendFormat": "comp-cpu-store"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"nersc-ldms-store-compute-gpu.+\"})",
     "legendFormat": "comp-gpu-store"
    },
    {
     "expr": "count(kube_pod_info{pod=~\"nersc-ldms-store-mana.+\"})",
     "legendFormat": "mana-store"
    }
   ]
  },
  {
   "title": "ldmsd-exporter (metric rate per minute per ldmsd)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "count(sum(count_over_time({job=\"nersc-ldms-exporter\"}[$__range])) by (pod))",
     "legendFormat": "metrics"
    }
   ]
  },
  {
   "title": "Metrics Per Sampler Plugin",
   "type": "timeseries",
   "description": "The number of metrics per sampler type",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 33 },
   "targets": [
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_dcgm_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "dcgm"
    },
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_vmstat_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "vmstat"
    },
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_procnetdev_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "procnetdev"
    },
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_meminfo_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "meminfo"
    },
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_procstat_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "procstat"
    },
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_loadavg_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "loadavg"
    },
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_slingshot_info_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "slingshot_info"
    },
    {
     "expr": "count(group by(__name__) ({__name__=~\"nersc_ldms_slingshot_metrics_.+\", hostname=~\"nid001001|nid001088|nid001008\"}))",
     "legendFormat": "slingshot_metrics"
    }
   ]
  },
  { "title": "CPU/Mem/NET", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "CPU - Agg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"sma\", pod=~\"nersc-ldms-aggr-.+\"}) by (container),\n    \"container\",\n    \"init\",\n    \"container\",\n    \"^$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - Agg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(container_memory_working_set_bytes{namespace=\"sma\", pod=~\"nersc-ldms-aggr-.+\", container!=\"\", image!=\"\"}) by (container),\n    \"container\",\n    \"init\",\n    \"container\",\n    \"^$\"\n)",
     "legendFormat": "nersc - {{container}}"
    }
   ]
  },
  {
   "title": "Network - Agg",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"sma\", pod=~\"nersc-ldms-aggr-.+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"sma\", pod=~\"nersc-ldms-aggr-.+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "TX Bytes"
    }
   ]
  },
  {
   "title": "CPU - Store",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"sma\", pod=~\"nersc-ldms-store-.+\"}) by (pod),\n    \"container\",\n    \"init\",\n    \"container\",\n    \"^$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - Store",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(container_memory_working_set_bytes{namespace=\"sma\", pod=~\"nersc-ldms-store-.+\", container!=\"\", image!=\"\"}) by (pod),\n    \"container\",\n    \"init\",\n    \"container\",\n    \"^$\"\n)",
     "legendFormat": "nersc - {{container}}"
    }
   ]
  },
  {
   "title": "Network - Store",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"sma\", pod=~\"nersc-ldms-store.+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"sma\", pod=~\"nersc-ldms-store.+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "TX Bytes"
    }
   ]
  },
  {
   "title": "CPU - Stream",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "cpu" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace=\"sma\", pod=~\"nersc-ldms-stream-.+\"}) by (pod),\n    \"container\",\n    \"init\",\n    \"container\",\n    \"^$\"\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - Stream",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(\n    sum(container_memory_working_set_bytes{namespace=\"sma\", pod=~\"nersc-ldms-stream-.+\", container!=\"\", image!=\"\"}) by (pod),\n    \"container\",\n    \"init\",\n    \"container\",\n    \"^$\"\n)",
     "legendFormat": "nersc - {{container}}"
    }
   ]
  },
  {
   "title": "Network - Stream",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(container_network_receive_bytes_total{namespace=\"sma\", pod=~\"nersc-ldms-stream.+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "RX Bytes"
    },
    {
     "expr": "sum(irate(container_network_transmit_bytes_total{namespace=\"sma\", pod=~\"nersc-ldms-stream.+\"}[$__rate_interval])) by (pod)",
     "legendFormat": "TX Bytes"
    }
   ]
  },
  { "title": "Kafka Topic: nersc_ldms", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Kafka messages in per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{topic=~\"nersc-ldms\", namespace=~\"sma\"}[1m])) by (topic)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kafka messages out per second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{consumergroup=~\"otg-vector-nersc-ldms\",topic=~\"nersc-ldms\", namespace=~\"sma\"}[1m])/60) by (consumergroup, topic)",
     "legendFormat": "otg-vector-nersc-ldms (topic: nersc-ldms)"
    }
   ]
  },
  {
   "title": "Kafka consumer lag",
   "type": "timeseries",
   "description": "How far behind are consumers for the kafka topic nersc-ldms",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{consumergroup=~\"otg-vector-nersc-ldms\",topic=\"nersc-ldms\", namespace=\"sma\"}) by (consumergroup, topic)",
     "legendFormat": "otg-vector-nersc-ldms (topic: nersc-ldms)"
    }
   ]
  },
  { "title": "LDMS Streams", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "ldms-stream (aka nerscjson)",
   "type": "logs",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 64 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{data_type=\"cray-logs-containers\", namespace=\"sma\",pod=\"nersc-ldms-stream-0\", container=\"stream\"}  |~ \"stream_type|hello_ldms_ms\" |json | line_format \"{{.message}}\"",
     "maxLines": 500
    }
   ]
  },
  { "title": "ldmsd log types", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 73 } },
  {
   "title": "NERSC Agg - connection error (per 2m)",
   "type": "timeseries",
   "description": "sum(count_over_time({data_type=\"cray-logs-containers\",namespace=\"sma\", pod=\"nersc-ldms-aggr-0\"} |= \"connection error to sock\" | pattern \"<_> Producer <hostname>: connection error to sock <_>\"[1m])) by (container,hostname)",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "targets": [
    {
     "expr": "sum_over_time(sum(VlogsContainerLog:NERSCConnError:1mCount) without (_time) [$__interval]) default 0",
     "legendFormat": "{{container}} - {{hostname}}"
    }
   ]
  },
  {
   "title": "NERSC Agg - is inconsistent (per 2m)",
   "type": "timeseries",
   "description": "Ran base_sample_begin(),  but have not reached base_sample_end()\n\nsum(count_over_time({data_type=\"cray-logs-containers\",namespace=\"sma\", pod=~\"nersc-ldms-aggr-0\"} |= \"is inconsistent\" |pattern \"<_>Set <hostname>/<metric> is inconsistent<_>\"[10m])) by(container, metric)",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "targets": [
    {
     "expr": "sum_over_time(sum(VlogsContainerLog:NERSCSetInconsistent:1mCount) without (_time) [$__interval]) default 0",
     "legendFormat": "{{container}} - {{metric}}"
    }
   ]
  },
  {
   "title": "NERSC Agg - outstanding update (per 2m)",
   "type": "timeseries",
   "description": "sum(count_over_time({data_type=\"cray-logs-containers\",namespace=\"sma\", pod=~\"nersc-ldms-aggr-0\"} |= \"there is an outstanding update\" |pattern \"<_>Set <hostname>/<metric>: there is an outstanding update<_>\"[10m])) by(container, metric)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum_over_time(sum(VlogsContainerLog:NERSCAggrOutstandingUpdate:1mCount) without (_time) [$__interval]) default 0",
     "legendFormat": "{{container}} - {{metric}}"
    }
   ]
  },
  {
   "title": "NERSC Agg - oversampling (per 2m)",
   "type": "timeseries",
   "description": "Oversampling: The update and previous contain the same sampleID.\n\nsum(count_over_time({data_type=\"cray-logs-containers\",namespace=\"sma\", pod=~\"nersc-ldms-aggr-0\"} |= \"oversampled\" |pattern \"<_>Set <hostname>/<metric> <_>\"[10m])) by(container, metric)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "sum_over_time(sum(VlogsContainerLog:NERSCOversampled:1mCount) without (_time) [$__interval]) default 0",
     "legendFormat": "{{container}} - {{metric}}"
    }
   ]
  }
 ]
}