[project]
name = "omnia_build_stream"
version = "1.0.0"
description = "Python environment for the Omnia Build Stream FastAPI container."
requires-python = ">= 3.11"
dependencies = [
    "fastapi>=0.115.6",
    "starlette>=0.49.1",
    "uvicorn[standard]>=0.34.0",
    "python-multipart==0.0.20",
    "requests==2.32.5",
    "pyyaml==6.0.3",
    "jmespath==1.0.1",
    "urllib3>=2.6.3",
    "pulp-cli[pygments]==0.33.0"
]
