# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Testinfra tests for build_image verification.

This file contains test functions that verify build_image deployment was successful.
Tests continue even if some fail (skip_on_failure behavior).

Validations:
1. functional_groups_config.yml exists and contains all roles/groups from pxe_mapping
2. Base and compute images are available in regctl registry
3. All 3 images (initrd, rootfs, vmlinuz) are pushed to S3 bucket for each functional group

Usage:
    ./run_molecule.sh build_image test      # Run playbook + verify
    ./run_molecule.sh build_image verify    # Verify only
"""

import pytest
from automation_library.core import TestLogger
from automation_library.build_image.vars import (
    BUILD_IMAGE_VARS,
    S3_CONTAINERS,
)
from automation_library.build_image.messages import (
    TEST_VARS,
    TEST_NAMES,
    TEST_LOG_MSGS as LOG_MSGS,
    TEST_ASSERT_MSGS as ASSERT_MSGS,
)
from automation_library.build_image.functions import (
    check_functional_group_file_exists,
    check_functional_group_content,
    check_regctl_registry_images,
    check_s3_bucket_images,
    get_functional_groups_from_container,
)


# =============================================================================
# FUNCTIONAL GROUP VALIDATION TESTS
# =============================================================================

def test_functional_groups_config_autogenerated(host):
    """Validate that functional_groups_config.yml is autogenerated correctly."""
    log = TestLogger(TEST_NAMES["functional_group_autogenerated"])
    file_path = BUILD_IMAGE_VARS["functional_group_file_path"]
    log.check(f"Checking file is autogenerated: {file_path}")

    result = check_functional_group_file_exists(host)

    if result["success"]:
        log.passed(
            LOG_MSGS["functional_group_file_exists"].format(path=file_path),
            result["details"]
        )
    else:
        log.failed(
            LOG_MSGS["functional_group_file_not_found"].format(path=file_path),
            result["error"]
        )

    assert result["success"], ASSERT_MSGS["functional_group_file_not_found"].format(
        path=file_path, status=result["status"]
    )


def test_functional_group_content(host):
    """Verify functional_groups_config.yml contains all roles and groups from pxe_mapping."""
    log = TestLogger(TEST_NAMES["functional_group_content"])
    file_path = BUILD_IMAGE_VARS["functional_group_file_path"]

    # First check if file exists - skip if not
    file_exists = check_functional_group_file_exists(host)
    if not file_exists["success"]:
        pytest.skip(f"Skipped - {file_path} does not exist (autogeneration failed)")

    expected_groups = get_functional_groups_from_container(host)
    log.check(f"Validating content against {len(expected_groups)} functional groups from pxe_mapping")

    result = check_functional_group_content(host)

    if result["success"]:
        log.passed(
            LOG_MSGS["functional_group_content_ok"].format(count=len(expected_groups)),
            result["details"]
        )
    else:
        missing = result.get("missing_functional_groups", []) + result.get("missing_group_names", [])
        log.failed(
            LOG_MSGS["functional_group_content_missing"].format(count=len(missing)),
            result["error"]
        )

    assert result["success"], ASSERT_MSGS["functional_group_content_missing"].format(
        missing=", ".join(result.get("missing_functional_groups", []) + result.get("missing_group_names", [])),
        expected_list="\n".join([f"║   - {g}" for g in expected_groups])
    )


# =============================================================================
# REGCTL REGISTRY VALIDATION TESTS
# =============================================================================

def test_regctl_registry_images(host):
    """Validate that base and compute images are available in regctl registry."""
    log = TestLogger(TEST_NAMES["regctl_registry_images"])
    functional_groups = get_functional_groups_from_container(host)
    log.check(f"Checking regctl registry for base image + {len(functional_groups)} functional group images")

    result = check_regctl_registry_images(host)

    if result["success"]:
        # Show details for each image
        log.passed(
            LOG_MSGS["regctl_registry_images_ok"],
            "\n    ".join(result["found_images"])
        )
    else:
        log.failed(
            LOG_MSGS["regctl_registry_images_missing"].format(count=len(result["missing_images"])),
            f"Missing: {', '.join(result['missing_images'])}"
        )

    assert result["success"], ASSERT_MSGS["regctl_registry_images_missing"].format(
        registry_url=result.get("registry_url", "unknown"),
        count=len(result["missing_images"]),
        missing_list="\n".join([f"║   - {img}" for img in result["missing_images"]])
    )


# =============================================================================
# S3 BUCKET VALIDATION TESTS
# =============================================================================

def test_s3_bucket_images(host):
    """Verify all images are pushed to S3 bucket for all functional groups."""
    log = TestLogger(TEST_NAMES["s3_bucket_images"])
    functional_groups = get_functional_groups_from_container(host)
    image_types = BUILD_IMAGE_VARS["image_types"]
    log.check(f"Checking S3 bucket for {len(functional_groups)} functional groups x {len(image_types)} images each")

    result = check_s3_bucket_images(host)

    # Print complete S3 bucket output
    s3_output = result.get("s3_output", "")
    if s3_output:
        print("\n  ┌─────────────────────────────────────────────────────────────────")
        print("  │ S3 BUCKET CONTENTS (s3cmd ls -Hr s3://boot-images):")
        print("  ├─────────────────────────────────────────────────────────────────")
        for line in s3_output.strip().split("\n"):
            print(f"  │ {line}")
        print("  └─────────────────────────────────────────────────────────────────")

    if result["success"]:
        # Show details for each group
        group_details = []
        for fg_result in result["results"]:
            group_details.append(f"{fg_result['functional_group']}: {', '.join(fg_result['found_images'])}")
        log.passed(LOG_MSGS["s3_bucket_images_ok"], "\n    ".join(group_details))
    else:
        # Build detailed failure message
        failed_groups = [r for r in result["results"] if not r["success"]]
        failure_details = []
        for fg_result in failed_groups:
            failure_details.append(
                f"{fg_result['functional_group']}: missing {', '.join(fg_result['missing_images'])}"
            )
        log.failed(
            LOG_MSGS["s3_bucket_images_missing"].format(count=len(failed_groups)),
            "; ".join(failure_details)
        )

    # Build assert message with details for each failed group
    if not result["success"]:
        failed_groups = [r for r in result["results"] if not r["success"]]
        assert_details = []
        for fg_result in failed_groups:
            assert_details.append(
                f"║   - {fg_result['functional_group']}: missing {', '.join(fg_result['missing_images'])}"
            )
        assert False, ASSERT_MSGS["s3_bucket_images_missing"].format(
            group="multiple groups",
            missing_list="\n".join(assert_details)
        )
