"""
Testinfra tests for build_image_x86_64 verification.

This file contains test functions that verify build_image_x86_64 deployment was successful.
Tests continue even if some fail (skip_on_failure behavior).

Validations:
    1. S3 containers are running without errors
    2. functional_group.yml is autogenerated correctly with roles/groups from pxe_mapping.csv
    3. Base and compute images are available in regctl registry
    4. Images are pushed to S3 bucket (all 3 images for each functional group)

Usage:
    ./run_molecule.sh build_image_x86_64 test      # Run playbook + verify
    ./run_molecule.sh build_image_x86_64 verify    # Verify only
"""

import pytest
from automation_library.core import TestLogger
from automation_library.vars.build_image_x86_64_vars import (
    S3_CONTAINERS,
    REGISTRY_CONTAINER,
    IMAGE_TYPES,
)
from automation_library.messages.build_image_x86_64_msgs import (
    TEST_VARS, TEST_NAMES, TEST_LOG_MSGS as LOG_MSGS, TEST_ASSERT_MSGS as ASSERT_MSGS
)
from automation_library.functions.build_image_x86_64_func import (
    check_s3_container_running,
    check_all_s3_containers,
    check_functional_group_exists,
    check_functional_group_valid,
    check_functional_group_roles,
    check_functional_group_groups,
    check_registry_container,
    check_regctl_available,
    check_base_image_in_registry,
    check_compute_image_in_registry,
    check_s3_bucket_accessible,
    check_s3_bucket_images,
    get_functional_groups,
    check_functional_group_images_in_s3,
)


# =============================================================================
# S3 CONTAINER TESTS
# =============================================================================

@pytest.mark.parametrize("container", S3_CONTAINERS)
def test_s3_container_running(host, container):
    """Verify S3 containers are running without any errors."""
    log = TestLogger(TEST_NAMES["s3_container_running"].format(container=container))
    log.check(f"Checking S3 container: {container}")

    result = check_s3_container_running(host, container)

    if result["success"]:
        log.passed(LOG_MSGS["s3_container_running"].format(container=container), result["status"])
    else:
        log.failed(LOG_MSGS["s3_container_not_running"].format(container=container), result["error"])

    assert result["success"], ASSERT_MSGS["s3_container_not_running"].format(
        container=container, status=result["status"]
    )


# =============================================================================
# FUNCTIONAL GROUP TESTS
# =============================================================================

def test_functional_group_exists(host):
    """Verify functional_group.yml file exists."""
    log = TestLogger(TEST_NAMES["functional_group_exists"])
    path = TEST_VARS["functional_group_path"]
    log.check(f"Checking if functional_group.yml exists at {path}")

    result = check_functional_group_exists(host)

    if result["success"]:
        log.passed(LOG_MSGS["functional_group_exists"].format(path=path), result["details"])
    else:
        log.failed(LOG_MSGS["functional_group_not_exists"].format(path=path), result["error"])

    assert result["success"], ASSERT_MSGS["functional_group_not_exists"].format(path=path)


def test_functional_group_valid_yaml(host):
    """Verify functional_group.yml is valid YAML."""
    log = TestLogger(TEST_NAMES["functional_group_valid"])
    path = TEST_VARS["functional_group_path"]
    log.check(f"Validating YAML syntax of {path}")

    result = check_functional_group_valid(host)

    if result["success"]:
        log.passed(LOG_MSGS["functional_group_valid"], result["details"])
    else:
        log.failed(LOG_MSGS["functional_group_invalid"].format(error=result["error"]), result["error"])

    assert result["success"], ASSERT_MSGS["functional_group_invalid"].format(
        path=path, error=result["error"]
    )


def test_functional_group_roles_from_pxe_mapping(host):
    """Verify functional_group.yml contains all roles from pxe_mapping.csv."""
    log = TestLogger(TEST_NAMES["functional_group_roles"])
    log.check("Checking if all roles from pxe_mapping.csv are in functional_group.yml")

    result = check_functional_group_roles(host)

    if result["success"]:
        log.passed(LOG_MSGS["functional_group_roles_ok"], result["details"])
    else:
        missing = ", ".join(result["missing"]) if result["missing"] else "unknown"
        log.failed(LOG_MSGS["functional_group_roles_missing"].format(missing=missing), result["error"])

    assert result["success"], ASSERT_MSGS["functional_group_roles_missing"].format(
        missing=", ".join(result["missing"]) if result["missing"] else "unknown"
    )


def test_functional_group_groups_from_pxe_mapping(host):
    """Verify functional_group.yml contains all groups from pxe_mapping.csv."""
    log = TestLogger(TEST_NAMES["functional_group_groups"])
    log.check("Checking if all groups from pxe_mapping.csv are in functional_group.yml")

    result = check_functional_group_groups(host)

    if result["success"]:
        log.passed(LOG_MSGS["functional_group_groups_ok"], result["details"])
    else:
        missing = ", ".join(result["missing"]) if result["missing"] else "unknown"
        log.failed(LOG_MSGS["functional_group_groups_missing"].format(missing=missing), result["error"])

    assert result["success"], ASSERT_MSGS["functional_group_roles_missing"].format(
        missing=", ".join(result["missing"]) if result["missing"] else "unknown"
    )


# =============================================================================
# REGISTRY TESTS
# =============================================================================

def test_registry_container_running(host):
    """Verify registry container is running."""
    log = TestLogger(TEST_NAMES["registry_container_running"])
    log.check(f"Checking registry container: {REGISTRY_CONTAINER}")

    result = check_registry_container(host)

    if result["success"]:
        log.passed(LOG_MSGS["registry_running"], result["status"])
    else:
        log.failed(LOG_MSGS["registry_not_running"], result["error"])

    assert result["success"], ASSERT_MSGS["registry_not_running"].format(
        status=result["status"]
    )


def test_regctl_available(host):
    """Verify regctl command is available."""
    log = TestLogger(TEST_NAMES["regctl_available"])
    log.check("Checking if regctl command is available")

    result = check_regctl_available(host)

    if result["success"]:
        log.passed(LOG_MSGS["regctl_available"], result["version"])
    else:
        log.failed(LOG_MSGS["regctl_not_available"], result["error"])

    assert result["success"], (
        "╔══════════════════════════════════════════════════════════════════════════════╗\n"
        "║ REGCTL COMMAND NOT AVAILABLE\n"
        "╠══════════════════════════════════════════════════════════════════════════════╣\n"
        "║ The regctl command is required to list registry images.\n"
        "║\n"
        "║ HOW TO FIX:\n"
        "║   1. Install regctl: https://github.com/regclient/regclient\n"
        "║   2. Verify installation: regctl version\n"
        "╚══════════════════════════════════════════════════════════════════════════════╝"
    )


def test_base_image_in_registry(host):
    """Verify base images are available in the regctl registry."""
    log = TestLogger(TEST_NAMES["base_image_in_registry"])
    log.check("Checking for base images in registry")

    result = check_base_image_in_registry(host)

    if result["success"]:
        images = ", ".join(result["images"]) if result["images"] else "found"
        log.passed(LOG_MSGS["base_image_found"].format(image=images), result["details"])
    else:
        log.failed(LOG_MSGS["base_image_not_found"].format(image="base"), result["error"])

    assert result["success"], ASSERT_MSGS["image_not_in_registry"].format(
        image="base", image_type="base"
    )


def test_compute_image_in_registry(host):
    """Verify compute images are available in the regctl registry."""
    log = TestLogger(TEST_NAMES["compute_image_in_registry"])
    log.check("Checking for compute images in registry")

    result = check_compute_image_in_registry(host)

    if result["success"]:
        images = ", ".join(result["images"]) if result["images"] else "found"
        log.passed(LOG_MSGS["compute_image_found"].format(image=images), result["details"])
    else:
        log.failed(LOG_MSGS["compute_image_not_found"].format(image="compute"), result["error"])

    assert result["success"], ASSERT_MSGS["image_not_in_registry"].format(
        image="compute", image_type="compute"
    )


# =============================================================================
# S3 BUCKET TESTS
# =============================================================================

def test_s3_bucket_accessible(host):
    """Verify S3 bucket is accessible."""
    log = TestLogger(TEST_NAMES["s3_bucket_accessible"])
    bucket = TEST_VARS["s3_bucket"]
    log.check(f"Checking S3 bucket accessibility: {bucket}")

    result = check_s3_bucket_accessible(host)

    if result["success"]:
        log.passed(LOG_MSGS["s3_bucket_accessible"].format(bucket=bucket), result["details"])
    else:
        log.failed(LOG_MSGS["s3_bucket_not_accessible"].format(bucket=bucket), result["error"])

    assert result["success"], ASSERT_MSGS["s3_bucket_not_accessible"].format(
        bucket=bucket, error=result["error"]
    )


def test_images_in_s3_bucket(host):
    """Verify images are pushed to S3 bucket using s3cmd ls -Hr s3://boot-images."""
    log = TestLogger(TEST_NAMES["images_in_s3"])
    bucket = TEST_VARS["s3_bucket"]
    log.check(f"Listing images in S3 bucket: s3cmd ls -Hr s3://{bucket}")

    result = check_s3_bucket_images(host)

    if result["success"]:
        log.passed(LOG_MSGS["images_in_s3"], f"Found {result['count']} items")
    else:
        log.failed(LOG_MSGS["images_not_in_s3"], result["error"])

    assert result["success"], ASSERT_MSGS["images_not_in_s3"].format(
        bucket=bucket, group="all", missing="images"
    )


def test_all_functional_group_images_in_s3(host):
    """Verify all 3 images for each functional group are in S3 bucket."""
    log = TestLogger("Verify all functional group images in S3")
    bucket = TEST_VARS["s3_bucket"]

    # Get functional groups
    groups = get_functional_groups(host)
    log.check(f"Found {len(groups)} functional groups to verify")

    if not groups:
        log.failed("No functional groups found", "functional_group.yml may be empty or invalid")
        pytest.skip("No functional groups found in functional_group.yml")

    all_passed = True
    failed_groups = []

    for group in groups:
        result = check_functional_group_images_in_s3(host, group)
        if result["success"]:
            log.passed(
                LOG_MSGS["functional_group_images_ok"].format(group=group),
                f"Found: {', '.join(result['found'])}"
            )
        else:
            all_passed = False
            failed_groups.append({
                "group": group,
                "missing": result["missing"]
            })
            log.failed(
                LOG_MSGS["functional_group_images_missing"].format(
                    group=group, missing=", ".join(result["missing"])
                ),
                result["error"]
            )

    if not all_passed:
        failed_details = "\n".join([
            f"║   - {fg['group']}: missing {', '.join(fg['missing'])}"
            for fg in failed_groups
        ])
        assert False, (
            f"╔══════════════════════════════════════════════════════════════════════════════╗\n"
            f"║ FUNCTIONAL GROUP IMAGES MISSING IN S3\n"
            f"╠══════════════════════════════════════════════════════════════════════════════╣\n"
            f"║ Bucket: {bucket}\n"
            f"║ Failed Groups:\n"
            f"{failed_details}\n"
            f"║\n"
            f"║ HOW TO FIX:\n"
            f"║   1. List S3 contents: s3cmd ls -Hr s3://boot-images\n"
            f"║   2. Check build logs for errors\n"
            f"║   3. Re-run build_image_x86_64.yml to push images\n"
            f"╚══════════════════════════════════════════════════════════════════════════════╝"
        )
