# Copyright 2026 Dell Inc. or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Slurm functions module.
"""

from .slurm_func import (
    get_job_script_path,
    parse_login_ips_from_env,
    parse_login_ips_from_pxe_mapping,
    parse_login_compiler_ips_from_env,
    parse_login_compiler_ips_from_pxe_mapping,
    parse_compute_node_ips_from_env,
    parse_compute_node_ips_from_pxe_mapping,
    parse_ldap_user_from_env,
    parse_ldap_key_path_from_env,
    is_node_reachable,
    run_ssh_from_omnia_core,
    submit_job_via_login,
    check_squeue,
    find_reachable_login_node,
    run_ssh_as_user,
    discover_ldap_user_from_node,
    create_ldap_job_script,
    submit_ldap_job,
    wait_ldap_job_complete,
    read_ldap_job_output,
    cleanup_ldap_job,
    submit_and_verify_ldap_job,
    check_pam_module_installed,
    check_pam_config,
    ssh_to_compute_as_user,
    submit_sleep_job_as_user,
    get_job_node,
    resolve_node_ip,
    cancel_job_as_user,
    check_user_processes_on_node,
    parse_slurm_control_ip_from_pxe_mapping,
    check_slurm_version,
    check_sinfo,
    read_job_script_by_name,
    copy_script_to_remote,
    submit_remote_script,
    poll_job_state,
    check_job_scontrol,
    read_job_output,
    cleanup_job,
    ssh_cmd_direct,
    get_compute_nodes,
    get_node_info,
    drain_node,
    resume_node,
    wait_node_state,
    create_job_script,
    submit_job_direct,
    poll_job_state_direct,
    wait_job_running,
    get_job_start_time,
    cleanup_jobs_direct,
    check_slurmctld_active,
    get_slurmctld_pid,
    submit_batch_jobs,
    count_queue_jobs,
    cancel_jobs_by_name,
    cancel_jobs_by_ids,
    submit_and_cancel_rapid,
    get_node_total_cpus,
    check_queue_empty,
    restart_slurmctld,
    check_no_zombie_slurmd,
    get_node_state,
)

__all__ = [
    "get_job_script_path",
    "parse_login_ips_from_env",
    "parse_login_ips_from_pxe_mapping",
    "parse_login_compiler_ips_from_env",
    "parse_login_compiler_ips_from_pxe_mapping",
    "parse_compute_node_ips_from_env",
    "parse_compute_node_ips_from_pxe_mapping",
    "parse_ldap_user_from_env",
    "parse_ldap_key_path_from_env",
    "is_node_reachable",
    "run_ssh_from_omnia_core",
    "submit_job_via_login",
    "check_squeue",
    "find_reachable_login_node",
    "run_ssh_as_user",
    "discover_ldap_user_from_node",
    "create_ldap_job_script",
    "submit_ldap_job",
    "wait_ldap_job_complete",
    "read_ldap_job_output",
    "cleanup_ldap_job",
    "submit_and_verify_ldap_job",
    "check_pam_module_installed",
    "check_pam_config",
    "ssh_to_compute_as_user",
    "submit_sleep_job_as_user",
    "get_job_node",
    "resolve_node_ip",
    "cancel_job_as_user",
    "check_user_processes_on_node",
    "parse_slurm_control_ip_from_pxe_mapping",
    "check_slurm_version",
    "check_sinfo",
    "read_job_script_by_name",
    "copy_script_to_remote",
    "submit_remote_script",
    "poll_job_state",
    "check_job_scontrol",
    "read_job_output",
    "cleanup_job",
    "ssh_cmd_direct",
    "get_compute_nodes",
    "get_node_info",
    "drain_node",
    "resume_node",
    "wait_node_state",
    "create_job_script",
    "submit_job_direct",
    "poll_job_state_direct",
    "wait_job_running",
    "get_job_start_time",
    "cleanup_jobs_direct",
    "check_slurmctld_active",
    "get_slurmctld_pid",
    "submit_batch_jobs",
    "count_queue_jobs",
    "cancel_jobs_by_name",
    "cancel_jobs_by_ids",
    "submit_and_cancel_rapid",
    "get_node_total_cpus",
    "check_queue_empty",
    "restart_slurmctld",
    "check_no_zombie_slurmd",
    "get_node_state",
]
